import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./../../public/admin/css/app.min.css";
import "./../../public/admin/css/vendor.min.css";
import { Provider } from "react-redux";
import { store } from "@/redux/store";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
        <body className={inter.className}>{children}</body>
    </html>
  );
}
